# Generated by Django 4.2.7 on 2024-01-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0002_userprofile_first_name_userprofile_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
